import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile, copyFile } from "node:fs/promises";
import { registerHooks } from "node:module";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { initializeContentStore, setContentArchived, upsertContentItems } from "../lib/archive-store";
import { initializeMonitorStore, updateStoryReviews } from "../lib/monitor-store";
import { initializeAiUsageStore, startAiUsage } from "../lib/ai-usage-store";
import { initializeCollectorCache, writeCollectorSnapshot } from "../lib/collector-cache";
import { initializeIndustryStore } from "../lib/industry-store";
import { saveFeedback } from "../lib/feedback-store";
import { industryCacheScope } from "../lib/collector-scopes";
import { importScannerRun } from "../lib/scanner-store";
registerHooks({ resolve(specifier, context, next) { return specifier === "server-only" ? { url: "data:text/javascript,export {};", shortCircuit: true } : next(specifier, context); },
  load(url, context, next) { return url === "data:text/javascript,export {};" ? { format: "commonjs", source: "module.exports={};", shortCircuit: true } : next(url, context); } });
const timestamp = "2026-10-06T05:13:00.000Z";
test("scanner adapters and APIs read existing reports without network or AI, migrate schema 10, preserve choices and recover imports", async () => {
  const temp = await mkdtemp(path.join(os.tmpdir(), "cc-scanners-")), data = path.join(temp, "data"), geo = path.join(temp, "geo"), tanks = path.join(temp, "tanks");
  const oldData = process.env.CONTROL_CENTER_DATA_DIR, originalFetch = globalThis.fetch;
  const dbPath = path.join(data, "control-center.sqlite");
  await mkdir(data); await mkdir(path.join(geo, "briefs"), { recursive: true }); await mkdir(path.join(geo, "collections", "2026-10-06-050003-123456"), { recursive: true });
  const runId = "20261006T050003-fixture", reportDir = path.join(tanks, "reports", "runs", runId); await mkdir(reportDir, { recursive: true });
  const writeJson = (file: string, value: unknown) => writeFile(file, JSON.stringify(value));
  const markdown = "# Geoeconomics fixture\n\n*1 main story · Generated 05:00 AEDT*\n\nSaved summary from the producer.";
  await writeFile(path.join(geo, "briefs", "2026-10-06.md"), markdown);
  const source = new DatabaseSync(path.join(geo, "monitor.db"));
  source.exec("CREATE TABLE runs(run_id TEXT PRIMARY KEY,created_at TEXT,story_count INTEGER); CREATE TABLE stories(run_id TEXT,story_id TEXT,title TEXT,theme TEXT,significance TEXT,score INTEGER,payload_json TEXT)");
  source.prepare("INSERT INTO runs VALUES(?,?,?)").run("2026-10-06", timestamp, 1);
  source.prepare("INSERT INTO stories VALUES(?,?,?,?,?,?,?)").run("2026-10-06", "event-1", "Export controls implementation", "Export controls", "high", 12, JSON.stringify({ summary: "Existing producer summary", sources: [{ name: "Source", url: "https://example.org/evidence?utm_source=geo" }] })); source.close();
  const collectionDir = path.join(geo, "collections", "2026-10-06-050003-123456");
  await writeJson(path.join(collectionDir, "coverage.json"), { since: "2026-10-05T00:00:00Z", until: "2026-10-06T00:00:00Z", sources_requested: 2, requests_successful: 2 });
  await writeJson(path.join(collectionDir, "events.json"), [{ id: "event-1", stage: "main" }]);
  await writeJson(path.join(collectionDir, "classification.json"), { article: { item: { url: "https://example.org/evidence", published: "2026-10-05T12:00:00Z" } } });
  const manifest = { run_id: runId, run_date: "2026-10-06", edition: "daily", status: "complete", completed_at: timestamp, source_windows: { Source: { start: "2026-10-04T00:00:00Z" } }, coverage_end: "2026-10-06T00:00:00Z", source_status: { Source: "checked/found 1 item" } };
  await writeJson(path.join(tanks, "reports", "latest.json"), { run_id: runId, directory: "C:/outside/untrusted", manifest: "../../.env" });
  await writeJson(path.join(reportDir, "run.json"), manifest);
  const tankReport = { run_date: "2026-10-06", run: { run_id: runId }, reports: [{ title: "Think tank findings", institution: "Source", published_at_verified: "2026-10-05T12:00:00Z", url: "https://example.org/evidence", summary: "Existing tank summary", importance_score: 4, tags: ["Economic security"] }], events: [], podcasts: [] };
  await writeJson(path.join(reportDir, "report_2026-10-06.json"), tankReport); await writeFile(path.join(reportDir, "report_2026-10-06.md"), "# Think tank fixture\nExisting summary");
  const settingsText = JSON.stringify({ general: { workspaceName: "Fixture" }, industry: { sources: [{ id: "source", name: "Source", url: "https://example.org/feed" }], keywords: ["Export controls"], lookbackDays: 3, dailyLimit: 15 }, ai: { provider: "none" }, newsletters: { refreshToken: "fixture-private-token", connectedEmail: "fixture@example.org" } });
  await writeFile(path.join(data, "settings.json"), settingsText);
  process.env.CONTROL_CENTER_DATA_DIR = data;
  let requests = 0; globalThis.fetch = (async () => { requests++; throw new Error("No network allowed for status or scanner controls"); }) as typeof fetch;
  try {
    const old = initializeAiUsageStore(initializeIndustryStore(initializeCollectorCache(initializeMonitorStore(initializeContentStore(new DatabaseSync(dbPath))))));
    upsertContentItems(old, "industry", [{ id: "existing", title: "Existing evidence", source: "Source", summary: "Existing", publishedAt: "2026-10-05T12:00:00Z", url: "https://example.org/evidence" }]);
    updateStoryReviews(old, { ids: ["existing"], saved: true, reviewed: true }); setContentArchived(old, "industry", "existing", true);
    saveFeedback(old, { storyId: "existing", choice: "useful", expectedId: null, reason: "Private feedback" }, ["Export controls"]);
    startAiUsage(old, "fixture-model", "monitor ranking"); old.exec("PRAGMA user_version=10"); old.close();
    const { getDatabase } = await import("../lib/server/database"); const db = getDatabase();
    assert.equal(db.prepare("PRAGMA user_version").get()?.user_version, 11);
    const migrations = await readdir(path.join(data, "migration-backups")); assert.equal(migrations.length, 1);
    const before = new DatabaseSync(path.join(data, "migration-backups", migrations[0]), { readOnly: true }); assert.equal(before.prepare("PRAGMA user_version").get()?.user_version, 10); before.close();
    const { GET, POST, PUT } = await import("../app/api/scanners/route");
    const { GET: status, PUT: controls } = await import("../app/api/collection-status/route");
    const { GET: monitor } = await import("../app/api/live/industry/route");
    const { readSettings } = await import("../lib/server/settings");
    const { trackCollection } = await import("../lib/server/collection-tracking");
    const request = (input: unknown, method = "POST") => new Request("http://127.0.0.1:3000/api/scanners", { method, body: JSON.stringify(input) });
    assert.equal((await PUT(request({ producer: "geoeconomics", directory: geo }, "PUT"))).status, 200);
    assert.equal((await PUT(request({ producer: "think-tanks", directory: tanks }, "PUT"))).status, 200);
    const baselineSourceBytes = await readFile(path.join(geo, "monitor.db"));
    const { readGeoeconomics } = await import("../lib/server/scanner-connectors");
    await readGeoeconomics(geo);
    const viewResponse = await GET(new Request("http://127.0.0.1/api/scanners?producer=geoeconomics"));
    const view = await viewResponse.json(); assert.equal(viewResponse.status, 200, JSON.stringify(view));
    assert.equal(view.items[0].summary, "Existing producer summary"); assert.equal(view.items[0].publishedAt, "2026-10-05T12:00:00.000Z");
    const tanksView = await (await GET(new Request("http://127.0.0.1/api/scanners?producer=think-tanks"))).json(); assert.equal(tanksView.run.id, runId);
    assert.equal((await GET(new Request("http://127.0.0.1/api/scanners?producer=think-tanks&run=../../.env"))).status, 400);
    const imported = await (await POST(request({ action: "import-latest", producer: "geoeconomics" }))).json(); assert.equal(imported.updated, 1);
    const repeat = await (await POST(request({ action: "import-latest", producer: "geoeconomics" }))).json(); assert.equal(repeat.alreadyImported, true);
    assert.equal((await POST(request({ action: "import-latest", producer: "think-tanks" }))).status, 200);
    assert.equal(db.prepare("SELECT count(*) AS n FROM content_items").get()?.n, 1);
    const stored = await (await GET(new Request("http://127.0.0.1/api/scanners?producer=geoeconomics&run=2026-10-06&stored=1"))).json(); assert.equal(stored.run.briefMarkdown, markdown);
    const bad = structuredClone(view); bad.items[0].sources[0].url = "file:///private";
    assert.equal((await POST(request({ report: bad }))).status, 400);
    await writeJson(path.join(reportDir, "run.json"), { ...manifest, status: "failed" }); assert.equal((await POST(request({ action: "import-latest", producer: "think-tanks" }))).status, 409);
    assert.equal(db.prepare("SELECT count(*) AS n FROM scanner_runs").get()?.n, 2);
    const statusPayload = await (await status()).json(); assert.equal(statusPayload.schedule.autoImport, false); assert.ok(!JSON.stringify(statusPayload).includes("fixture-private-token"));
    const paused = await (await controls(request({ automatic: false, autoImport: true }, "PUT"))).json(); assert.equal(paused.schedule.nextAt, null);
    assert.equal((await controls(request({ automatic: "yes", autoImport: false }, "PUT"))).status, 400);
    let work = 0;
    const task = () => { work++; return new Promise<Response>((resolve) => setTimeout(() => resolve(Response.json({ configured: true, items: [], errors: [], pendingIssueCount: 5 })), 15)); };
    await Promise.all([trackCollection("newsletters", task), trackCollection("newsletters", task)]); assert.equal(work, 1, "overlapping checks share one collection");
    const finished = await (await status()).json(); assert.equal(finished.modules.find((row: { module: string }) => row.module === "newsletters").pending, 5);
    const settings = await readSettings(); writeCollectorSnapshot(db, "industry", industryCacheScope(settings), { configured: true, checkedAt: timestamp, items: [], errors: [], freshnessHours: 72 });
    const savedFeed = await (await monitor(new Request("http://127.0.0.1/api/live/industry"))).json(); assert.equal(savedFeed.archivedItems[0].review.savedAt !== null, true); assert.equal(savedFeed.archivedItems[0].scannerSources.length, 2);
    assert.equal(await readFile(path.join(data, "settings.json"), "utf8"), settingsText); assert.deepEqual(await readFile(path.join(geo, "monitor.db")), baselineSourceBytes);
    assert.equal(requests, 0); assert.equal(db.prepare("SELECT count(*) AS n FROM ai_usage").get()?.n, 1);
    const restorePath = path.join(temp, "restored.sqlite"); db.exec("PRAGMA wal_checkpoint(TRUNCATE)"); await copyFile(dbPath, restorePath);
    const restored = new DatabaseSync(restorePath); try { assert.equal(restored.prepare("PRAGMA integrity_check").get()?.integrity_check, "ok"); assert.equal(restored.prepare("SELECT count(*) AS n FROM scanner_runs").get()?.n, 2); assert.equal(importScannerRun(restored, view).alreadyImported, true); } finally { restored.close(); }
  } finally {
    globalThis.controlCenterDatabase?.close(); globalThis.controlCenterDatabase = undefined;
    globalThis.controlCenterTrackedCollections = undefined; globalThis.fetch = originalFetch;
    if (oldData === undefined) delete process.env.CONTROL_CENTER_DATA_DIR; else process.env.CONTROL_CENTER_DATA_DIR = oldData;
    assert.ok(path.resolve(temp).startsWith(path.resolve(os.tmpdir()) + path.sep)); await rm(temp, { recursive: true, force: true });
  }
});
